"""empty message

Revision ID: 674bc89b4a78
Revises: e1d770c37c41
Create Date: 2021-02-20 15:03:40.540040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '674bc89b4a78'
down_revision = 'e1d770c37c41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=240), nullable=False),
    sa.Column('price', sa.Float(precision=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
